server:
    error:
      include-message: always
      include-binding-errors: always

#spring:
#  datasource:
#      url: jdbc:postgresql://localhost:5432/registration
#      username: postgres
#      password: shrijan
#
#      jpa:
#      hibernate:
#        ddl-auto: create-drop
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.PostgreSQLDialect
#            format_sql: true
#          show-sql: true

spring:
  datasource:
    password: shrijan
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    generate-ddl: false






